import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import type { InferGetServerSidePropsType, GetServerSideProps } from "next";
import styles from "../styles/Home.module.css";
import { Pool, Client } from "pg";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps: GetServerSideProps<{}> = async () => {
  // for connection information
  const pool = new Pool();

  // you can also use async/await
  const res = await pool.query("SELECT * from public.todo");
  await pool.end();

  return { props: { rows: res.rows } };
};

export default function Home(props: any) {
  console.log(props.rows);
  const todoData = props.rows;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {todoData.map((todo: any) => {
            return <li key={todo.id}>{todo.title}</li>;
          })}
        </ul>
      </main>
    </>
  );
}
