import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const todoData = [{
    id: 1,
    title: "Todo One"
  }];
  return (
    <>
      <Head>
        <title>Todo One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {todoData.map((todo: any) => {
            return <li key={todo.id}>{todo.title}</li>;
          })}
        </ul>
      </main>
    </>
  );
}
